### ISSUE TITLE
Warning under Elixir 1.16

### ISSUE THREAD

**Issue by halostatue** [hrzndhrn/datix#13]
Elixir 1.16 is presenting a new warning with the following code:

```elixir
iex> format = Datix.compile!("%a %b %d %H:%M:%S %Z %Y")
iex> {:ok, ~D[2020-09-25]} == Datix.Date.parse("Fri Sep 25 00:00:00 EDT 2020", format)
warning: negative steps are not supported in String.slice/2, pass 3..-1//1 instead
  (elixir 1.16.3) lib/string.ex:2369: String.slice/2
  (datix 0.3.1) lib/datix.ex:458: Datix.parse_string/4
  (datix 0.3.1) lib/datix.ex:295: Datix.parse_date_time/4
  (datix 0.3.1) lib/datix.ex:276: Datix.parse/4
  (datix 0.3.1) lib/datix.ex:132: Datix.strptime/3
  (datix 0.3.1) lib/datix/date.ex:95: Datix.Date.parse/3

warning: negative steps are not supported in String.slice/2, pass 3..-1//1 instead
  (elixir 1.16.3) lib/string.ex:2369: String.slice/2
  (datix 0.3.1) lib/datix.ex:458: Datix.parse_string/4
  (datix 0.3.1) lib/datix.ex:295: Datix.parse_date_time/4
  (datix 0.3.1) lib/datix.ex:276: Datix.parse/4
  (datix 0.3.1) lib/datix.ex:132: Datix.strptime/3
  (datix 0.3.1) lib/datix/date.ex:95: Datix.Date.parse/3
true
```

This fixes it:

```diff
diff --git i/lib/datix.ex w/lib/datix.ex
index 89c8af09fcec..b248fd55391b 100644
--- i/lib/datix.ex
+++ w/lib/datix.ex
@@ -453,11 +453,11 @@ defmodule Datix do
   defp parse_string(_str, _padding, [], _pos), do: {:error, %ParseError{reason: :invalid_string}}
 
   defp parse_string(str, padding, [item | list], pos) do
     case String.starts_with?(str, item) do
       false -> parse_string(str, padding, list, pos + 1)
-      true -> {:ok, pos + 1, String.slice(str, String.length(item)..-1)}
+      true -> {:ok, pos + 1, String.slice(str, String.length(item)..-1//1)}
     end
   end
 
   defp parse_upcase_string(str, padding, acc \\ [])
 
```

**Comment by NickNeck** [comment]
Thank you for your report. I will have a look.
