### ISSUE TITLE
ArithmeticError when parsing %Z

### ISSUE THREAD

**Issue by wojtekmach** [hrzndhrn/datix#3]
```elixir
Mix.install([
  {:datix, "0.1.1"}
])

Datix.DateTime.parse!("2022-08-02 09:10:00 CEST", "%Y-%m-%d %H:%M:%S %Z")
|> IO.inspect()
```

```
** (ArithmeticError) bad argument in arithmetic expression: nil * -1
    :erlang.*(nil, -1)
    (datix 0.1.1) lib/datix/date_time.ex:123: Datix.DateTime.time_zone/2
    (datix 0.1.1) lib/datix/date_time.ex:86: Datix.DateTime.parse!/3
    datix.exs:5: (file)
```

**Comment by NickNeck** [comment]
Thanks for reporting. I will take a look.
